const products = [
    {
        id: 1,
        name: 'Neon Genesis Evangelion Deluxe 12',
        price: 77.22,
        image: './assets/Books/M1.png',
        categoryId: 2,
        author: 'Yoshiyuki Sadamoto',
        editorial: 'Ivrea',
        year: 2016,
        language: 'Español',
        pages: 180,
        binding: 'Tapa Blanda',
        synopsis: 'Una edición deluxe de la famosa serie de Evangelion, con ilustraciones exclusivas y una narrativa que mezcla ciencia ficción y drama psicológico.'
    },
    {
        id: 2,
        name: 'Oyasumi Pun Pun Tomo 02',
        price: 64.00,
        image: './assets/Books/M2.png',
        categoryId: 2,
        author: 'Inio Asano',
        editorial: 'Astiberri',
        year: 2014,
        language: 'Español',
        pages: 192,
        binding: 'Tapa Blanda',
        synopsis: 'La compleja y emotiva historia de Punpun, un joven que enfrenta las dificultades de la vida, el amor y la soledad en una sociedad que lo rechaza.'
    },
    {
        id: 3,
        name: 'SHUUMATSU NO VALKYRIE 02',
        price: 40.50,
        image: './assets/Books/M3.png',
        categoryId: 2,
        author: 'Takumi Fukui',
        editorial: 'IVREA',
        year: 2020,
        language: 'Español',
        pages: 200,
        binding: 'Tapa Blanda',
        synopsis: 'En un mundo donde los dioses luchan contra los humanos, este volumen continúa la feroz batalla entre figuras mitológicas y guerreros legendarios.'
    },
    {
        id: 4,
        name: 'El amor, las mujeres y la vida',
        price: 73.49,
        image: './assets/Books/P1.png',
        categoryId: 4,
        author: 'Mario Benedetti',
        editorial: 'Alfaguara',
        year: 1994,
        language: 'Español',
        pages: 120,
        binding: 'Tapa Blanda',
        synopsis: 'Una reflexión profunda sobre el amor, las mujeres y las complejidades de la vida, escrita con la prosa única de Mario Benedetti.'
    },
    {
        id: 5,
        name: 'Rimas y Leyendas',
        price: 22.73,
        image: './assets/Books/P2.png',
        categoryId: 4,
        author: 'Gustavo Adolfo Bécquer',
        editorial: 'Cátedra',
        year: 2010,
        language: 'Español',
        pages: 300,
        binding: 'Tapa Blanda',
        synopsis: 'Una obra maestra del Romanticismo que reúne las famosas rimas y leyendas de Bécquer, cargadas de emoción y misterio.'
    },
    {
        id: 6,
        name: 'Veinte poemas de amor y una canción desesperada',
        price: 48.00,
        image: './assets/Books/P3.png',
        categoryId: 4,
        author: 'Pablo Neruda',
        editorial: 'Losada',
        year: 1924,
        language: 'Español',
        pages: 104,
        binding: 'Tapa Blanda',
        synopsis: 'Una colección de poemas que expresa los sentimientos más profundos sobre el amor y la desolación, escrita por uno de los poetas más grandes de la lengua española.'
    },
    {
        id: 7,
        name: 'La Divina Comedia',
        price: 66.93,
        image: './assets/Books/P4.png',
        categoryId: 4,
        author: 'Dante Alighieri',
        editorial: 'Ediciones Akal',
        year: 1995,
        language: 'Español',
        pages: 450,
        binding: 'Tapa Dura',
        synopsis: 'El poema épico de Dante Alighieri que relata el viaje a través del Infierno, el Purgatorio y el Paraíso, una alegoría de la vida y el destino humano.'
    },
    {
        id: 8,
        name: 'Donde viven las musas',
        price: 110.36,
        image: './assets/Books/A1.png',
        categoryId: 5,
        author: 'Varios Autores',
        editorial: 'Varios',
        year: 2020,
        language: 'Español',
        pages: 150,
        binding: 'Tapa Blanda',
        synopsis: 'Una antología de textos inspiradores, que exploran la vida, la creatividad y la influencia de las musas en el arte y la literatura.'
    },
    {
        id: 9,
        name: 'El Asombroso Spiderman',
        price: 82.80,
        image: './assets/Books/C1.png',
        categoryId: 3,
        author: 'Stan Lee y Steve Ditko',
        editorial: 'Marvel Comics',
        year: 1962,
        language: 'Español',
        pages: 100,
        binding: 'Tapa Blanda',
        synopsis: 'La primera aparición de Spider-Man, un héroe atrapado entre la responsabilidad de ser un adolescente normal y la de luchar contra el crimen.'
    },
    {
        id: 10,
        name: 'La metamorfosis y otros cuentos',
        price: 38.00,
        image: './assets/Books/L1.png',
        categoryId: 6,
        author: 'Franz Kafka',
        editorial: 'Varias',
        year: 1946,
        language: 'Español',
        pages: 150,
        binding: 'Tapa Blanda',
        synopsis: 'La famosa obra de Kafka donde el protagonista se transforma en un insecto, junto con otros relatos de angustia y alienación.'
    },
    {
        id: 11,
        name: 'Cien años de soledad (edición ilustrada)',
        price: 103.33,
        image: './assets/Books/N1.png',
        categoryId: 1,
        author: 'Gabriel García Márquez',
        editorial: 'Random House',
        year: 2014,
        language: 'Español',
        pages: 400,
        binding: 'Tapa Dura',
        synopsis: 'La obra maestra de García Márquez que relata la historia de la familia Buendía a través de siete generaciones en el mítico pueblo de Macondo.'
    },
    {
        id: 12,
        name: 'El Libro de Bill',
        price: 63.92,
        image: './assets/Books/C2.png',
        categoryId: 6,
        author: 'Bill Watterson',
        editorial: 'Varios',
        year: 2024,
        language: 'Español',
        pages: 120,
        binding: 'Tapa Blanda',
        synopsis: 'Una colección de las tiras cómicas de Calvin y Hobbes, donde Bill Watterson reflexiona sobre la vida, la naturaleza y la infancia.'
    }
];
